services:
  - type: web
    name: merobazar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn retail.wsgi.application
    postDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
