# Generated by Django 5.1.7 on 2025-04-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_brand_product_image_supplier_address_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
