# Generated by Django 5.1.7 on 2025-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restock',
            options={'get_latest_by': 'restock_date'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
